### ISSUE TITLE
Change to maintained version of cosmiconfig-typescript-loader

### ISSUE THREAD

**Issue by Codex-** [kamilkisiela/graphql-config#1039] opened 2022-04-29 06:17 UTC
**Is your feature request related to a problem? Please describe.**

`graphql-config` depends on the abandoned packages [`@endemolshinegroup/cosmiconfig-typescript-loader`](https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader).

This package has a number of issues opened against it, and the maintaining company has been absorbed and are no longer maintaining this package.

**Describe the solution you'd like**

I actively maintain and publish a replacement [`cosmiconfig-typescript-loader`](https://github.com/Codex-/cosmiconfig-typescript-loader).

You can find more information about the replacement package, and the issues it resolves here: https://github.com/Codex-/cosmiconfig-typescript-loader#endemolshinegroupcosmiconfig-typescript-loader

I have made the change on a fork and am happy to open a PR if you would be happy to accept this as a replacement. You can view the change here: https://github.com/Codex-/graphql-config/commit/5139382ddf025221ce9fb92efbaf2c600cca2707

**Comment by 72636c** [comment] 2022-06-22 22:27
`@endemolshinegroup/cosmiconfig-typescript-loader`'s outdated dependency on `ts-node` 9 now errors under TypeScript 4.7:

```ts
/workdir/node_modules/typescript/lib/typescript.js:42537
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
                 ^
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/workdir/node_modules/typescript/lib/typescript.js:42537:18)
    at /workdir/node_modules/@endemolshinegroup/cosmiconfig-typescript-loader/node_modules/ts-node/src/index.ts:623:55
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/workdir/node_modules/@endemolshinegroup/cosmiconfig-typescript-loader/node_modules/ts-node/src/index.ts:622:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/workdir/node_modules/typescript/lib/typescript.js:116674:163)
    at resolveTypeReferenceDirectiveNamesWorker (/workdir/node_modules/typescript/lib/typescript.js:116974:26)
    at processTypeReferenceDirectives (/workdir/node_modules/typescript/lib/typescript.js:118456:31)
    at findSourceFileWorker (/workdir/node_modules/typescript/lib/typescript.js:118341:21)
    at findSourceFile (/workdir/node_modules/typescript/lib/typescript.js:118196:26)
    at processImportedModules (/workdir/node_modules/typescript/lib/typescript.js:118602:25)
```

**Comment by Codex-** [comment] 2022-06-22 23:05
I noticed that the consuming code for the old loader has to coerce out the default, I'm releasing a new version of the loader later today / tomorrow that will now include both esm and cjs to ease this pain point.

**Comment by vhiairrassary** [comment] 2022-06-26 12:54
We have the same issue on our side: we can't upgrade to the latest versions of TypeScript & Jest, due to `ts-node` 9 being pulled by `@endemolshinegroup/cosmiconfig-typescript-loader` (which seems to be unmaintained, and used by `graphql-config`). 

Unfortunately, npm's `override` is still broken (see https://github.com/npm/cli/issues/4232, even if the issue is marked as `Closed`) so we cannot set `ts-node` to `10.x.y` in our workspaces.

**Comment by Codex-** [comment] 2022-06-26 22:07
Opened #1069 to address this.

**Closed** 2022-06-27 07:02 UTC
Labels: enhancement, dependencies
